spring:
  application:
    name: setlist-to-playlist
  profiles:
    include:
      - oauth
logging:
  level:
    org.example.setlisttoplaylist: DEBUG

spotify:
  static:
    client-id: "${SPOTIFY_STATIC_CLIENT_ID:}"
    client-secret: "${SPOTIFY_STATIC_CLIENT_SECRET:}"
    refresh-token: "${SPOTIFY_STATIC_REFRESH_TOKEN:}"

setlistfm:
  base-url: "https://api.setlist.fm/rest/1.0"
  api-key: "${SETLIST_FM_API_KEY:}"
---
spring:
  config.activate.on-profile: local
app:
  domain: "http://127.0.0.1:5173"
---
spring:
  config.activate.on-profile: prod
app:
  domain: "https://setlist-to-playlist.fly.dev"
